<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426115530 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE perte (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, raison VARCHAR(255) NOT NULL, date_perte TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_12F685F8F347EFB ON perte (produit_id)');
        $this->addSql('CREATE TABLE produit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, prix_achat NUMERIC(10, 2) NOT NULL, prix_vente NUMERIC(10, 2) NOT NULL, quantite_stock INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE vente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, date_vente TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_888A2A4CF347EFB ON vente (produit_id)');
        $this->addSql('ALTER TABLE perte ADD CONSTRAINT FK_12F685F8F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vente ADD CONSTRAINT FK_888A2A4CF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE perte DROP CONSTRAINT FK_12F685F8F347EFB');
        $this->addSql('ALTER TABLE vente DROP CONSTRAINT FK_888A2A4CF347EFB');
        $this->addSql('DROP TABLE perte');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE vente');
        $this->addSql('DROP INDEX UNIQ_8D93D649E7927C74');
    }
}
